'use client'
import type { Metadata } from 'next'

import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { createContext, useContext, useState } from 'react';

export const fileContext = createContext({})
const inter = Outfit({ subsets: ['latin'] })




 const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {

const [file, setFile] = useState(null);
const [fileId, setFileId] = useState(null);

  return (
  <fileContext.Provider value={{file, setFile, fileId, setFileId}}>
      
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
    </fileContext.Provider>

  )
}
